name: 'Dummy Action'
description: 'Test inputs / Ouputs'
inputs:
  my-input-arg:
    description: 'Input argument'
    required: false
    default: 'not provided'
runs:
  using: composite
  steps:
    - name: "Display an input argument"
      run:  echo "Input arg - ${{ inputs.my-input-arg }}"
      shell: bash
    - name: "Abort a workflow"
      run: exit 1
      shell: bash