name: First Workflow
on: [push, workflow_dispatch]
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello World
        run: |
          echo "Hello World"
          echo "Another Line"
      - name: Print a second step
        shell: python
        run: print("Woaw a python line")      
      - name: Get Info
        run: |
          hostname
          pwd
          ls -l /
      - name: Create a file
        run: |
          ls -al
          echo "One line" | tee myFile.log
          ls -al
      - name: A final step
        run: ls -al

  second-job:
    runs-on: ubuntu-latest
    env:
      MY_JOB_VAR: "This is the end"
    steps:
      - name: Test environment variable
        env:
          STEP_ENV_VAR: "This is a step variable"
        run: |
          echo "Value: ${{ vars.MY_ENV_VAR }}"
          echo "Job Value: $MY_JOB_VAR"
          echo "Secret: ${{ secrets.MY_SECRET_VAR }}"
      - name: Get GitHub context
        run: echo "${{ toJSON(github) }}"

      - name: Get value from context
        run: echo "${{ secrets.MY_SECRET_VAR }}"
        
  
