name: Second Workflow
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Get dependencies
        run: npm ci
      - name: Lint code
        run: npm run lint
      - name: List content
        run: ls -al
