name: Second Workflow
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Get dependencies
        run: npm ci
      - name: Lint code
        run: npm run lint
      - name: Run the server
        run: npm start & npx wait http://127.0.0.1:5173
      - name: Cypress Tests
        run: npx cypress run
