name: tbd-workflow
on:
  issues:
    types:
      - opened
jobs:
  bug-label:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Apply Bug Label
        env:
          TITLE: ${{ github.event.issue.title }}
        run: |
          title="$TITLE"
          if [[ "$title" == *"bug"* ]]; then
            curl --request POST \
            --url https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/labels \
            --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
            --header 'content-type: application/json' \
            --data '{
             "labels": ["bug"]
            }' \
            --fail
          fi